import { decouple, fromDefaults, fromDenoEnv } from "@denoboot/decouple/mod.ts";
import {
  ADMINS,
  ALLOWED_HOSTS,
  APPEND_SLASH,
  AUTH_USER_MODEL,
  AUTHENTICATION_BACKENDS,
  CACHE_MIDDLEWARE_ALIAS,
  CACHE_MIDDLEWARE_KEY_PREFIX,
  CACHE_MIDDLEWARE_SECONDS,
  CACHES,
  CSRF_COOKIE_AGE,
  CSRF_COOKIE_DOMAIN,
  CSRF_COOKIE_HTTPONLY,
  CSRF_COOKIE_NAME,
  CSRF_COOKIE_PATH,
  CSRF_COOKIE_SAMESITE,
  CSRF_COOKIE_SECURE,
  CSRF_TRUSTED_ORIGINS,
  CSRF_USE_SESSIONS,
  DATABASE_ROUTERS,
  DATABASES,
  DEBUG,
  DEBUG_PROPAGATE_EXCEPTIONS,
  DEFAULT_CHARSET,
  FORCE_SCRIPT_NAME,
  INSTALLED_APPS,
  INTERNAL_IPS,
  LANGUAGE_CODE,
  LANGUAGES,
  LANGUAGES_BIDI,
  LOCALE_PATHS,
  LOGGING,
  LOGGING_CONFIG,
  MANAGERS,
  MEDIA_ROOT,
  MEDIA_URL,
  MIDDLEWARE,
  PREPEND_WWW,
  SECRET_KEY,
  SECRET_KEY_FALLBACKS,
  SECURE_CONTENT_TYPE_NOSNIFF,
  SECURE_CROSS_ORIGIN_OPENER_POLICY,
  SECURE_CSP,
  SECURE_CSP_REPORT_ONLY,
  SECURE_HSTS_INCLUDE_SUBDOMAINS,
  SECURE_HSTS_PRELOAD,
  SECURE_HSTS_SECONDS,
  SECURE_REDIRECT_EXEMPT,
  SECURE_REFERRER_POLICY,
  SECURE_SSL_HOST,
  SECURE_SSL_REDIRECT,
  SESSION_COOKIE_AGE,
  SESSION_COOKIE_DOMAIN,
  SESSION_COOKIE_HTTPONLY,
  SESSION_COOKIE_NAME,
  SESSION_COOKIE_PATH,
  SESSION_COOKIE_SAMESITE,
  SESSION_COOKIE_SECURE,
  SESSION_ENGINE,
  SESSION_EXPIRE_AT_BROWSER_CLOSE,
  SESSION_SAVE_EVERY_REQUEST,
  SESSION_SERIALIZER,
  STATIC_ROOT,
  STATIC_URL,
  STATICFILES_DIRS,
  STATICFILES_FINDERS,
  TASKS,
  TEMPLATES,
  TIME_ZONE,
  USE_I18N,
  USE_TZ,
  USE_X_FORWARDED_HOST,
  USE_X_FORWARDED_PORT,
  X_FRAME_OPTIONS,
} from "./__internal/server-defaults.ts";

const config = decouple([
  fromDenoEnv(),
  fromDefaults({
    DEBUG,
    DEBUG_PROPAGATE_EXCEPTIONS,
    ADMINS,
    MANAGERS,
    INTERNAL_IPS,
    ALLOWED_HOSTS,
    TIME_ZONE,
    USE_TZ,
    LANGUAGE_CODE,
    LANGUAGES,
    LANGUAGES_BIDI,
    USE_I18N,
    LOCALE_PATHS,
    DEFAULT_CHARSET,
    APPEND_SLASH,
    PREPEND_WWW,
    FORCE_SCRIPT_NAME,
    X_FRAME_OPTIONS,
    USE_X_FORWARDED_HOST,
    USE_X_FORWARDED_PORT,
    SECRET_KEY,
    SECRET_KEY_FALLBACKS,
    SECURE_CONTENT_TYPE_NOSNIFF,
    SECURE_CROSS_ORIGIN_OPENER_POLICY,
    SECURE_HSTS_INCLUDE_SUBDOMAINS,
    SECURE_HSTS_PRELOAD,
    SECURE_HSTS_SECONDS,
    SECURE_REDIRECT_EXEMPT,
    SECURE_REFERRER_POLICY,
    SECURE_SSL_HOST,
    SECURE_SSL_REDIRECT,
    SECURE_CSP,
    SECURE_CSP_REPORT_ONLY,
    DATABASES,
    DATABASE_ROUTERS,
    CACHES,
    CACHE_MIDDLEWARE_KEY_PREFIX,
    CACHE_MIDDLEWARE_SECONDS,
    CACHE_MIDDLEWARE_ALIAS,
    INSTALLED_APPS,
    MIDDLEWARE,
    TEMPLATES,
    STATIC_ROOT,
    STATIC_URL,
    STATICFILES_DIRS,
    STATICFILES_FINDERS,
    MEDIA_ROOT,
    MEDIA_URL,
    LOGGING,
    LOGGING_CONFIG,
    SESSION_COOKIE_NAME,
    SESSION_COOKIE_AGE,
    SESSION_COOKIE_DOMAIN,
    SESSION_COOKIE_SECURE,
    SESSION_COOKIE_PATH,
    SESSION_COOKIE_HTTPONLY,
    SESSION_COOKIE_SAMESITE,
    SESSION_SAVE_EVERY_REQUEST,
    SESSION_EXPIRE_AT_BROWSER_CLOSE,
    SESSION_ENGINE,
    SESSION_SERIALIZER,
    AUTH_USER_MODEL,
    AUTHENTICATION_BACKENDS,
    CSRF_COOKIE_NAME,
    CSRF_COOKIE_AGE,
    CSRF_COOKIE_DOMAIN,
    CSRF_COOKIE_PATH,
    CSRF_COOKIE_SECURE,
    CSRF_COOKIE_HTTPONLY,
    CSRF_COOKIE_SAMESITE,
    CSRF_TRUSTED_ORIGINS,
    CSRF_USE_SESSIONS,
    TASKS,
  }),
]);

export default config;

export const globalCommonDefaults = {};
export const globalClientDefaults = {};

export const globalServerSettings = {
  // core
  core: {
    debug: config.bool("DEBUG", DEBUG),
    debugPropagateExceptions: config.bool("DEBUG_PROPAGATE_EXCEPTIONS", DEBUG_PROPAGATE_EXCEPTIONS),
    admins: config.list("ADMINS", ADMINS),
    managers: config.list("MANAGERS", config.list("ADMINS", ADMINS)),
    internalIps: config.list("INTERNAL_IPS", INTERNAL_IPS),
    allowedHosts: config.list("ALLOWED_HOSTS", ALLOWED_HOSTS),
    timeZone: config.string("TIME_ZONE", TIME_ZONE),
    useTz: config.bool("USE_TZ", USE_TZ),
    languageCode: config.string("LANGUAGE_CODE", LANGUAGE_CODE),
    languages: config.list("LANGUAGES", LANGUAGES),
    languagesBidi: config.list("LANGUAGES_BIDI", LANGUAGES_BIDI),
    useI18n: config.bool("USE_I18N", USE_I18N),
    localePaths: config.list("LOCALE_PATHS", LOCALE_PATHS),
  },
  // http
  http: {
    defaultCharset: config.string("DEFAULT_CHARSET", DEFAULT_CHARSET),
    appendSlash: config.bool("APPEND_SLASH", APPEND_SLASH),
    prependWww: config.bool("PREPEND_WWW", PREPEND_WWW),
    forceScriptName: config.string("FORCE_SCRIPT_NAME", FORCE_SCRIPT_NAME),
    xFrameOptions: config.string("X_FRAME_OPTIONS", X_FRAME_OPTIONS),
    useXForwardedHost: config.bool("USE_X_FORWARDED_HOST", USE_X_FORWARDED_HOST),
    useXForwardedPort: config.bool("USE_X_FORWARDED_PORT", USE_X_FORWARDED_PORT),
  },
  // security
  security: {
    securityKey: config.string("SECRET_KEY", SECRET_KEY),
    securityKeyFallbacks: config.list("SECRET_KEY_FALLBACKS", SECRET_KEY_FALLBACKS),
    secureContentTypeNoSniff: config.bool("SECURE_CONTENT_TYPE_NOSNIFF", SECURE_CONTENT_TYPE_NOSNIFF),
    secureHstsIncludeSubdomains: config.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", SECURE_HSTS_INCLUDE_SUBDOMAINS),
    secureHstsPreload: config.bool("SECURE_HSTS_PRELOAD", SECURE_HSTS_PRELOAD),
    secureHstsSeconds: config.number("SECURE_HSTS_SECONDS", SECURE_HSTS_SECONDS),
    secureRedirectExempt: config.list("SECURE_REDIRECT_EXEMPT", SECURE_REDIRECT_EXEMPT),
    secureSslHost: config.string("SECURE_SSL_HOST", SECURE_SSL_HOST),
    secureSslRedirect: config.bool("SECURE_SSL_REDIRECT", SECURE_SSL_REDIRECT),
    secureCsp: config.json("SECURE_CSP", SECURE_CSP),
    secureCspReportOnly: config.json("SECURE_CSP_REPORT_ONLY", SECURE_CSP_REPORT_ONLY),
  },
  // database
  database: {
    databases: config.json("DATABASES", DATABASES),
    databaseRouters: config.list("DATABASE_ROUTERS", DATABASE_ROUTERS),
  },
  // cache
  cache: {
    caches: config.json("CACHES", CACHES),
    cacheMiddlewareKeyPrefix: config.string("CACHE_MIDDLEWARE_KEY_PREFIX", CACHE_MIDDLEWARE_KEY_PREFIX),
    cacheMiddlewareSeconds: config.number("CACHE_MIDDLEWARE_SECONDS", CACHE_MIDDLEWARE_SECONDS),
    cacheMiddlewareAlias: config.string("CACHE_MIDDLEWARE_ALIAS", CACHE_MIDDLEWARE_ALIAS),
  },
  // application
  application: {
    plugins: config.list("plugins", INSTALLED_APPS),
    middleware: config.list("middleware", MIDDLEWARE),
    templates: config.list("templates", TEMPLATES),
  },
  // static
  static: {
    staticRoot: config.string("STATIC_ROOT", STATIC_ROOT),
    staticUrl: config.string("STATIC_URL", STATIC_URL),
    staticfilesDirs: config.list("STATICFILES_DIRS", STATICFILES_DIRS),
    staticfilesFinders: config.list("STATICFILES_FINDERS", STATICFILES_FINDERS),
  },
  // media
  media: {
    mediaRoot: config.string("MEDIA_ROOT", MEDIA_ROOT),
    mediaUrl: config.string("MEDIA_URL", MEDIA_URL),
  },
  // logging
  logging: {
    options: config.json("LOGGING", LOGGING),
    config: config.string("LOGGING_CONFIG", LOGGING_CONFIG),
  },
  // sessions
  sessions: {
    sessionCookieName: config.string("SESSION_COOKIE_NAME", SESSION_COOKIE_NAME),
    sessionCookieAge: config.number("SESSION_COOKIE_AGE", SESSION_COOKIE_AGE),
    sessionCookieDomain: config.string("SESSION_COOKIE_DOMAIN", SESSION_COOKIE_DOMAIN),
    sessionCookieSecure: config.bool("SESSION_COOKIE_SECURE", SESSION_COOKIE_SECURE),
    sessionCookiePath: config.string("SESSION_COOKIE_PATH", SESSION_COOKIE_PATH),
    sessionCookieHttpOnly: config.bool("SESSION_COOKIE_HTTPONLY", SESSION_COOKIE_HTTPONLY),
    sessionCookieSameSite: config.string("SESSION_COOKIE_SAMESITE", SESSION_COOKIE_SAMESITE),
    sessionSaveEveryRequest: config.bool("SESSION_SAVE_EVERY_REQUEST", SESSION_SAVE_EVERY_REQUEST),
    sessionExpireAtBrowserClose: config.bool("SESSION_EXPIRE_AT_BROWSER_CLOSE", SESSION_EXPIRE_AT_BROWSER_CLOSE),
    sessionEngine: config.string("SESSION_ENGINE", SESSION_ENGINE),
    sessionSerializer: config.string("SESSION_SERIALIZER", SESSION_SERIALIZER),
  },
  // auth
  auth: {},
  // csrf
  csrf: {
    csrfCookieName: config.string("CSRF_COOKIE_NAME", CSRF_COOKIE_NAME),
    csrfCookieAge: config.number("CSRF_COOKIE_AGE", CSRF_COOKIE_AGE),
    csrfCookieDomain: config.string("CSRF_COOKIE_DOMAIN", CSRF_COOKIE_DOMAIN),
    csrfCookiePath: config.string("CSRF_COOKIE_PATH", CSRF_COOKIE_PATH),
    csrfCookieSecure: config.bool("CSRF_COOKIE_SECURE", CSRF_COOKIE_SECURE),
    csrfCookieHttpOnly: config.bool("CSRF_COOKIE_HTTPONLY", CSRF_COOKIE_HTTPONLY),
    csrfCookieSameSite: config.string("CSRF_COOKIE_SAMESITE", CSRF_COOKIE_SAMESITE),
    csrfCookieTrustedOrigins: config.list("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS),
    csrfUseSessions: config.bool("CSRF_USE_SESSIONS", CSRF_USE_SESSIONS),
  },
  // tasks
  tasks: {},
};

export type GlobalServerSettings = typeof globalServerSettings;
